import type { NotationEntry } from "./notationTypes";

export const attentionNotation = {
  "attention-qkv-projection": {
    id: "attention-qkv-projection",
    title: "QKV Projection",
    plainText: "Z_qkv = Linear_qkv(X)",
    tex: "Z_{\\mathrm{qkv}} = \\operatorname{Linear}_{\\mathrm{qkv}}(X)",
    diagramDetail: "Linear: [T, C] → [T, 3C]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, 3C]",
    accessibleName: "QKV Projection, 하나의 Linear layer",
    description: "하나의 Linear 연산이 combined QKV tensor를 만듭니다.",
  },
  "attention-query": {
    id: "attention-query",
    title: "Query Q",
    plainText: "Q = Split_Q(Z_qkv)",
    tex: "Q = \\operatorname{Split}_Q(Z_{\\mathrm{qkv}})",
    diagramDetail: "Q [T, C]",
    symbolicInput: "[T, 3C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Query tensor Q",
    description: "Combined QKV tensor에서 Query tensor를 분리합니다.",
  },
  "attention-key": {
    id: "attention-key",
    title: "Key K",
    plainText: "K = Split_K(Z_qkv)",
    tex: "K = \\operatorname{Split}_K(Z_{\\mathrm{qkv}})",
    diagramDetail: "K [T, C]",
    symbolicInput: "[T, 3C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Key tensor K",
    description: "Combined QKV tensor에서 Key tensor를 분리합니다.",
  },
  "attention-value": {
    id: "attention-value",
    title: "Value V",
    plainText: "V = Split_V(Z_qkv)",
    tex: "V = \\operatorname{Split}_V(Z_{\\mathrm{qkv}})",
    diagramDetail: "V [T, C]",
    symbolicInput: "[T, 3C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Value tensor V",
    description: "Combined QKV tensor에서 Value tensor를 분리합니다.",
  },
  "attention-scores": {
    id: "attention-scores",
    title: "Score MatMul",
    plainText: "S_h = Q_h @ K_hᵀ",
    tex: "S_h = Q_h K_h^{\\mathsf T}",
    diagramDetail: "S_h = Q_h @ K_hᵀ",
    symbolicInput: "[T, D] @ [D, T]",
    symbolicOutput: "[T, T]",
    accessibleName: "Score MatMul, Query와 전치된 Key의 행렬곱",
    description:
      "선택한 head의 Query와 전치된 Key를 행렬곱해 attention score를 만듭니다.",
  },
  "attention-scale": {
    id: "attention-scale",
    title: "Scale",
    plainText: "S_h^scaled = S_h / √D",
    tex: "S_h^{\\mathrm{scaled}} = \\frac{S_h}{\\sqrt D}",
    diagramDetail: "S_h / √D",
    symbolicInput: "[T, T]",
    symbolicOutput: "[T, T]",
    accessibleName: "Scale, score를 head dimension 제곱근으로 나누기",
    description: "Score를 head dimension의 제곱근으로 나눕니다.",
  },
  "attention-causal-mask": {
    id: "attention-causal-mask",
    title: "Causal Mask",
    plainText: "S_h^masked = CausalMask(S_h^scaled)",
    tex: "S_h^{\\mathrm{masked}} = \\operatorname{CausalMask}(S_h^{\\mathrm{scaled}})",
    diagramDetail: "future positions blocked",
    symbolicInput: "[T, T]",
    symbolicOutput: "[T, T]",
    accessibleName: "Causal Mask, 미래 token position 차단",
    description: "현재 Query보다 뒤인 미래 위치의 score를 차단합니다.",
  },
  "attention-softmax": {
    id: "attention-softmax",
    title: "Softmax",
    plainText: "A_h = softmax(S_h^masked)",
    tex: "A_h = \\operatorname{softmax}(S_h^{\\mathrm{masked}})",
    diagramDetail: "A_h = softmax(S_h^masked)",
    symbolicInput: "[T, T]",
    symbolicOutput: "[T, T]",
    accessibleName: "Softmax, attention probability 정규화",
    description:
      "허용된 score를 선택한 head의 attention probability로 정규화합니다.",
  },
  "attention-value-aggregation": {
    id: "attention-value-aggregation",
    title: "Value MatMul",
    plainText: "Y_h = A_h @ V_h",
    tex: "Y_h = A_h V_h",
    diagramDetail: "Y_h = A_h @ V_h",
    symbolicInput: "[T, T] @ [T, D]",
    symbolicOutput: "[T, D]",
    accessibleName: "Value MatMul, attention probability와 Value의 행렬곱",
    description:
      "Attention probability와 Value를 행렬곱해 선택한 head output을 만듭니다.",
  },
  "attention-merge-heads": {
    id: "attention-merge-heads",
    title: "Merge Heads",
    plainText: "Y_merge = Concat(Y_0, …, Y_{H-1})",
    tex: "Y_{\\mathrm{merge}} = \\operatorname{Concat}(Y_0, \\ldots, Y_{H-1})",
    diagramDetail: "[H, T, D] → [T, C]",
    symbolicInput: "[H, T, D]",
    symbolicOutput: "[T, C]",
    accessibleName: "Merge Heads, head output 연결과 reshape",
    description:
      "Head output을 더하지 않고 Concat한 뒤 model dimension으로 reshape합니다.",
  },
  "attention-output-projection": {
    id: "attention-output-projection",
    title: "Output Projection",
    plainText: "Y_attn = Linear_out(Y_merge)",
    tex: "Y_{\\mathrm{attn}} = \\operatorname{Linear}_{\\mathrm{out}}(Y_{\\mathrm{merge}})",
    diagramDetail: "Linear: [T, C] → [T, C]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Output Projection, Linear C to C",
    description: "Output projection이 최종 attention output을 만듭니다.",
  },
} satisfies Readonly<Record<string, NotationEntry>>;
