import type { NotationEntry } from "./notationTypes";

export const blockNotation = {
  "layer-norm-1": {
    id: "layer-norm-1",
    title: "LayerNorm 1",
    plainText: "X_LN1 = LN1(X_in)",
    tex: "X_{\\mathrm{LN1}} = \\operatorname{LN1}(X_{\\mathrm{in}})",
    diagramDetail: "X_LN1 = LN1(X_in)",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "LayerNorm 1, Block 입력 정규화",
    description: "Block 입력 X_in을 attention 계산 전에 정규화합니다.",
  },
  "self-attention": {
    id: "self-attention",
    title: "Causal Multi-Head Self-Attention",
    plainText: "Y_attn = Attention(X_LN1)",
    tex: "Y_{\\mathrm{attn}} = \\operatorname{Attention}(X_{\\mathrm{LN1}})",
    diagramDetail: "Y_attn = Attention(X_LN1)",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Causal Multi-Head Self-Attention",
    description:
      "정규화된 입력에서 causal attention output Y_attn을 계산합니다.",
  },
  "residual-1": {
    id: "residual-1",
    title: "Residual 1",
    plainText: "X_res1 = X_in + Y_attn",
    tex: "X_{\\mathrm{res1}} = X_{\\mathrm{in}} + Y_{\\mathrm{attn}}",
    diagramDetail: "X_res1 = X_in + Y_attn",
    symbolicInput: "[T, C] + [T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "첫 번째 residual 덧셈",
    description: "Block 입력과 attention output을 원소별로 더합니다.",
  },
  "layer-norm-2": {
    id: "layer-norm-2",
    title: "LayerNorm 2",
    plainText: "X_LN2 = LN2(X_res1)",
    tex: "X_{\\mathrm{LN2}} = \\operatorname{LN2}(X_{\\mathrm{res1}})",
    diagramDetail: "X_LN2 = LN2(X_res1)",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "LayerNorm 2, 첫 residual 결과 정규화",
    description: "첫 residual 결과를 MLP 계산 전에 정규화합니다.",
  },
  mlp: {
    id: "mlp",
    title: "MLP",
    plainText: "Y_MLP = MLP(X_LN2)",
    tex: "Y_{\\mathrm{MLP}} = \\operatorname{MLP}(X_{\\mathrm{LN2}})",
    diagramDetail: "Y_MLP = MLP(X_LN2)",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "MLP feed-forward network",
    description: "정규화된 residual stream을 position-wise MLP로 변환합니다.",
  },
  "residual-2": {
    id: "residual-2",
    title: "Residual 2",
    plainText: "X_out = X_res1 + Y_MLP",
    tex: "X_{\\mathrm{out}} = X_{\\mathrm{res1}} + Y_{\\mathrm{MLP}}",
    diagramDetail: "X_out = X_res1 + Y_MLP",
    symbolicInput: "[T, C] + [T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "두 번째 residual 덧셈",
    description: "첫 residual 결과와 MLP output을 원소별로 더합니다.",
  },
} satisfies Readonly<Record<string, NotationEntry>>;
