import type { NotationEntry } from "./notationTypes";

export const rootNotation = {
  root: {
    id: "root",
    title: "GPT",
    plainText: "X_N = Block_{N-1}(…Block₀(X₀))",
    tex: "X_N = \\operatorname{Block}_{N-1}(\\ldots \\operatorname{Block}_0(X_0))",
    diagramDetail: "[T] → [T, Vocab]",
    symbolicInput: "[T]",
    symbolicOutput: "[T, Vocab]",
    accessibleName: "GPT Architecture",
    description:
      "현재 context가 logits와 다음 token으로 변환되는 전체 경로입니다.",
  },
  "input-context": {
    id: "input-context",
    title: "Input Context",
    plainText: "tokens = [t₀, …, t_{T-1}]",
    tex: "\\mathrm{tokens} = [t_0, \\ldots, t_{T-1}]",
    diagramDetail: "tokens [T]",
    symbolicInput: "[T]",
    symbolicOutput: "[T]",
    accessibleName: "현재 input token sequence",
    description: "현재 forward pass에 입력되는 token ID sequence입니다.",
  },
  "token-embedding": {
    id: "token-embedding",
    title: "Token Embedding",
    plainText: "E_tok = W_E[tokens]",
    tex: "E_{\\mathrm{tok}} = W_E[\\mathrm{tokens}]",
    diagramDetail: "[T] → [T, C]",
    symbolicInput: "[T]",
    symbolicOutput: "[T, C]",
    accessibleName: "Token embedding lookup",
    description: "각 token ID를 model dimension C의 vector로 변환합니다.",
  },
  "position-embedding": {
    id: "position-embedding",
    title: "Position Embedding",
    plainText: "E_pos = W_P[0:T]",
    tex: "E_{\\mathrm{pos}} = W_P[0:T]",
    diagramDetail: "[T] → [T, C]",
    symbolicInput: "[T]",
    symbolicOutput: "[T, C]",
    accessibleName: "Position embedding lookup",
    description:
      "각 sequence position을 model dimension C의 vector로 변환합니다.",
  },
  "embedding-add": {
    id: "embedding-add",
    title: "Embedding Add",
    plainText: "X₀ = E_tok + E_pos",
    tex: "X_0 = E_{\\mathrm{tok}} + E_{\\mathrm{pos}}",
    diagramDetail: "[T, C] + [T, C] → [T, C]",
    symbolicInput: "[T, C] + [T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Token과 Position embedding의 원소별 덧셈",
    description:
      "두 embedding을 원소별로 더해 초기 hidden state X₀를 만듭니다.",
  },
  "hidden-state": {
    id: "hidden-state",
    title: "Hidden State X₀",
    plainText: "X₀ = E_tok + E_pos",
    tex: "X_0 = E_{\\mathrm{tok}} + E_{\\mathrm{pos}}",
    diagramDetail: "[T, C]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "초기 hidden state X zero",
    description:
      "모든 Transformer Block에 들어가는 초기 residual stream입니다.",
  },
  "transformer-block": {
    id: "transformer-block",
    title: "Transformer Block",
    plainText: "X_N = Block_{N-1}(…Block₀(X₀))",
    tex: "X_N = \\operatorname{Block}_{N-1}(\\ldots \\operatorname{Block}_0(X_0))",
    diagramDetail: "[T, C] → [T, C]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "반복 Transformer Blocks",
    description: "구성된 N개 Block을 순서대로 적용합니다.",
  },
  "final-layer-norm": {
    id: "final-layer-norm",
    title: "Final LayerNorm",
    plainText: "X_final = LN_f(X_N)",
    tex: "X_{\\mathrm{final}} = \\operatorname{LN}_f(X_N)",
    diagramDetail: "[T, C] → [T, C]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, C]",
    accessibleName: "Final LayerNorm",
    description: "모든 Block을 지난 hidden state X_N을 정규화합니다.",
  },
  "lm-head": {
    id: "lm-head",
    title: "LM Head",
    plainText: "L = Linear_vocab(X_final)",
    tex: "L = \\operatorname{Linear}_{\\mathrm{vocab}}(X_{\\mathrm{final}})",
    diagramDetail: "Linear: [T, C] → [T, Vocab]",
    symbolicInput: "[T, C]",
    symbolicOutput: "[T, Vocab]",
    accessibleName: "LM Head Linear projection",
    description: "Final hidden state를 vocabulary logits로 projection합니다.",
  },
  logits: {
    id: "logits",
    title: "Logits",
    plainText: "L",
    tex: "L",
    diagramDetail: "L [T, Vocab]",
    symbolicInput: "[T, Vocab]",
    symbolicOutput: "[T, Vocab]",
    accessibleName: "Vocabulary logits",
    description: "각 token position의 vocabulary score입니다.",
  },
  "token-selection": {
    id: "token-selection",
    title: "Token Selection",
    plainText: "i_next ~ Select(L_last)",
    tex: "i_{\\mathrm{next}} \\sim \\operatorname{Select}(L_{\\mathrm{last}})",
    diagramDetail: "[Vocab] → [1]",
    symbolicInput: "[Vocab]",
    symbolicOutput: "[1]",
    accessibleName: "다음 token 선택",
    description: "마지막 position logits에서 다음 token ID를 선택합니다.",
  },
  "generated-token": {
    id: "generated-token",
    title: "Generated Token",
    plainText: "t_next = decode(i_next)",
    tex: "t_{\\mathrm{next}} = \\operatorname{decode}(i_{\\mathrm{next}})",
    diagramDetail: "token [1]",
    symbolicInput: "[1]",
    symbolicOutput: "[1]",
    accessibleName: "생성된 token",
    description: "선택한 token ID를 text piece로 decode합니다.",
  },
  "append-context": {
    id: "append-context",
    title: "Append to Context",
    plainText: "tokens′ = tokens ⧺ i_next",
    tex: "\\mathrm{tokens}' = \\mathrm{tokens} \\mathbin{\\Vert} i_{\\mathrm{next}}",
    diagramDetail: "[T], [1] → [T+1]",
    symbolicInput: "[T], [1]",
    symbolicOutput: "[T+1]",
    accessibleName: "생성 token을 context에 추가",
    description:
      "다음 forward pass를 위해 생성 token을 context 끝에 추가합니다.",
  },
} satisfies Readonly<Record<string, NotationEntry>>;
