#!/usr/bin/env bash
set -euo pipefail

readonly ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly PUBLIC_URL="${1:-/}"
readonly DIST_DIR="${2:-${ROOT_DIR}/apps/web/dist}"
readonly CANONICAL_REFERENCE_DIR="${ROOT_DIR}/reference/nanoGPT"
readonly PUBLIC_REFERENCE_DIR="${ROOT_DIR}/apps/web/public/reference"
readonly CSP="default-src 'self'; base-uri 'self'; object-src 'none'; script-src 'self' 'wasm-unsafe-eval'; style-src 'self'; img-src 'self' data:; font-src 'self'; connect-src 'self'; worker-src 'self'; manifest-src 'self'; form-action 'none'"
readonly REFERRER_POLICY="strict-origin-when-cross-origin"

case "${PUBLIC_URL}" in
  / | /*/) ;;
  *)
    printf 'Public URL must begin and end with a slash: %s\n' "${PUBLIC_URL}" >&2
    exit 2
    ;;
esac

for asset in model.py LICENSE; do
  cmp "${CANONICAL_REFERENCE_DIR}/${asset}" "${PUBLIC_REFERENCE_DIR}/${asset}"
done
(
  cd "${PUBLIC_REFERENCE_DIR}"
  shasum -a 256 -c SHA256SUMS
)

cd "${ROOT_DIR}/apps/web"
env NO_COLOR=true trunk build --release --public-url "${PUBLIC_URL}" --dist "${DIST_DIR}"

# Trunk emits one inline module bootstrap. Hash its exact generated bytes so CSP stays strict without
# allowing arbitrary inline scripts. Parsing and shape checks deliberately fail closed on tool changes.
python3 - "${DIST_DIR}/index.html" "${PUBLIC_URL}" "${CSP}" <<'PY'
import base64
import hashlib
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

page = Path(sys.argv[1])
public_url, base_policy = sys.argv[2:]
source = page.read_text(encoding="utf-8")

class Document(HTMLParser):
    def __init__(self):
        super().__init__()
        self.metas = []
        self.scripts = []
        self.current_script = None

    def handle_starttag(self, tag, attrs):
        if tag == "meta":
            self.metas.append(dict(attrs))
        elif tag == "script":
            if self.current_script is not None:
                raise ValueError("nested script tag")
            self.current_script = [dict(attrs), []]

    def handle_data(self, data):
        if self.current_script is not None:
            self.current_script[1].append(data)

    def handle_endtag(self, tag):
        if tag == "script":
            if self.current_script is None:
                raise ValueError("script end without start")
            attrs, parts = self.current_script
            self.scripts.append((attrs, "".join(parts)))
            self.current_script = None

def parse(document):
    parsed = Document()
    parsed.feed(document)
    parsed.close()
    if parsed.current_script is not None:
        raise ValueError("unterminated script")
    return parsed

parsed = parse(source)
csp_metas = [
    meta
    for meta in parsed.metas
    if meta.get("http-equiv", "").lower() == "content-security-policy"
]
if csp_metas or base_policy in source:
    raise SystemExit("development template must not supply a release CSP")
if len(parsed.scripts) != 1:
    raise SystemExit("expected exactly one Trunk inline bootstrap script")
attributes, bootstrap = parsed.scripts[0]
if attributes != {"type": "module"}:
    raise SystemExit("unexpected Trunk bootstrap attributes")
prefix = re.escape(public_url)
expected_bootstrap = re.compile(
    r"\nimport init, \* as bindings from '" + prefix + r"app-(?P<digest>[0-9a-f]+)\.js';\n"
    r"const wasm = await init\(\{ module_or_path: '" + prefix + r"app-(?P=digest)_bg\.wasm' \}\);\n\n\n"
    r"window\.wasmBindings = bindings;\n\n\n"
    r"dispatchEvent\(new CustomEvent\(\"TrunkApplicationStarted\", \{detail: \{wasm\}\}\)\);\n\n"
)
if expected_bootstrap.fullmatch(bootstrap) is None:
    raise SystemExit("unexpected Trunk bootstrap content")
digest = base64.b64encode(hashlib.sha256(bootstrap.encode("utf-8")).digest()).decode("ascii")
script_source = "script-src 'self' 'wasm-unsafe-eval'"
if base_policy.count(script_source) != 1:
    raise SystemExit("expected exactly one script-src directive")
policy = base_policy.replace(script_source, f"{script_source} 'sha256-{digest}'")
head_close = "</head>"
if source.count(head_close) != 1:
    raise SystemExit("expected exactly one HTML head")
csp_meta = f'<meta http-equiv="Content-Security-Policy" content="{policy}" />'
rendered = source.replace(head_close, f"    {csp_meta}\n  {head_close}", 1)
verified = parse(rendered)
expected_meta = {"http-equiv": "Content-Security-Policy", "content": policy}
if rendered.count(policy) != 1 or verified.metas.count(expected_meta) != 1:
    raise SystemExit("failed to inject the bootstrap CSP hash")
if rendered.index(csp_meta) > rendered.index("<script"):
    raise SystemExit("CSP meta must precede the bootstrap script")
page.write_text(rendered, encoding="utf-8")
PY

grep -Fq "<base href=\"${PUBLIC_URL}\"" "${DIST_DIR}/index.html"
grep -Fq "name=\"referrer\" content=\"${REFERRER_POLICY}\"" "${DIST_DIR}/index.html"
for pattern in '*.css' '*.js' '*.wasm' '*.safetensors'; do
  if ! find "${DIST_DIR}" -type f -name "${pattern}" -print -quit | grep -q .; then
    printf 'Static bundle is missing %s\n' "${pattern}" >&2
    exit 1
  fi
done

for asset in config.json manifest.json model.safetensors SHA256SUMS source_map.json tokenizer.json; do
  test -f "${DIST_DIR}/models/edu/${asset}"
done
for asset in model.py LICENSE; do
  test -f "${DIST_DIR}/reference/${asset}"
  cmp "${CANONICAL_REFERENCE_DIR}/${asset}" "${DIST_DIR}/reference/${asset}"
done
(
  cd "${DIST_DIR}/reference"
  shasum -a 256 -c SHA256SUMS
)

if find "${DIST_DIR}" -type f \( -name '*.py' -o -name '*.pyc' -o -name '*.sh' \) ! -path "${DIST_DIR}/reference/model.py" -print -quit | grep -q .; then
  printf 'Static bundle contains a build-time or server-side executable outside the pinned source reference.\n' >&2
  exit 1
fi
if grep -Eiq '(src|href)="(https?:)?//' "${DIST_DIR}/index.html"; then
  printf 'Static entry point contains a cross-origin runtime asset.\n' >&2
  exit 1
fi

python3 "${ROOT_DIR}/scripts/browser_release_ready.py" --root "${DIST_DIR}" --base "${PUBLIC_URL}"

printf 'Static bundle ready at %s for public URL %s\n' "${DIST_DIR}" "${PUBLIC_URL}"
